Blabster\Application\UseCase\Command\User\Login\UserLoginCommand:
    properties:
        email:
            - NotBlank: ~
            - Email: ~
        otp_uuid:
            - NotBlank: ~
            - Uuid: ~
        otp_code:
            - NotBlank: ~
